services:
  SymfonyLab\DoctrineOrmExtensionsBundle\Doctrine\MutableListener:
    public: false
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  SymfonyLab\DoctrineOrmExtensionsBundle\Doctrine\SoftDeleteableListener:
    public: false
    tags:
      - { name: doctrine.event_listener, event: preFlush, method: preFlush }

